config/routes.rb
Rails.application.routes.draw do

  root 'start#home'

  get 'start/home', as: :home
  get 'start/taco', as: :taco
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/start_controller.rb
class StartController < ApplicationController

  def home
  end

  def taco
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>#TacoTuesday</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<footer>
  <h3><%= link_to 'Designed by Dwight', "http://www.designsbydwight.com" %> for a <%= Time.now.year %> <%= link_to 'Iron Yard Academy Asignment', "http://theironyard.com" %></h3>
</footer>
</body>
</html>

app/views/start/home.html.erb
<div class="jumbotron">
  <h1>#TacoTuesday</h1>
  <figure class="dino">
  <%= link_to image_tag('makemeatacodino.png'), taco_path, :class => 'img-responsive' %></figure>
</div>

app/views/start/taco.html.erb
<div class="jumbotron">
<h1>Taco is Made!</h1>
<figure class="dino">
<%= link_to image_tag('makemeatacodinothanks.png'), home_path, :class => 'img-responsive' %></figure>
</div>